BIN_DIR := bin
SRC_DIR := src/kernel
SDCARD_DIR := sdcard
PROD_DIR := prod

C_SRCS = $(shell find $(SRC_DIR) -type f -name '*.c') 
ASM_SRCS = $(shell find $(SRC_DIR) -type f -name '*.S')
OBJS = $(patsubst $(SRC_DIR)/%.c, $(BIN_DIR)/%.o, $(C_SRCS)) \
       $(patsubst $(SRC_DIR)/%.S, $(BIN_DIR)/%_s.o, $(ASM_SRCS))

TARGET := exe
KERNEL_IMG := $(PROD_DIR)/kernel8-pi4.img
ARMSTUB_BIN := $(PROD_DIR)/armstub.bin

CC := aarch64-none-elf-gcc
LINKER := aarch64-none-elf-ld
OBJCOPY := aarch64-none-elf-objcopy

CFLAGS := -Wall -nostdlib -nodefaultlibs -nostartfiles -fno-builtin -ffreestanding \
          -mgeneral-regs-only -O0 -mstrict-align
INCLUDES := -I $(SRC_DIR)/include/
LINKERFILE := $(SRC_DIR)/linker.ld

# ANSI colors
BLUE   := \033[1;34m
GREEN  := \033[1;32m
YELLOW := \033[1;33m
RESET  := \033[0m

DEBUG ?= 0
ifeq ($(DEBUG), 1)
    CFLAGS += -DDEBUG -g
endif

# OS Detection for mounting
UNAME_S := $(shell uname -s)
MOUNT_PREFACE :=
ifeq ($(UNAME_S),Linux)
  MOUNT_PREFACE = u
endif

.PHONY: all local debug clean asm read

all: $(KERNEL_IMG) $(ARMSTUB_BIN)
	@printf "$(BLUE)==> Mounting SD card$(RESET)\n"
	./${MOUNT_PREFACE}scripts/mount.sh
	@printf "$(BLUE)==> Copying files to SD card$(RESET)\n"
	@mkdir -p $(SDCARD_DIR)
	cp -r $(PROD_DIR)/* $(SDCARD_DIR)/
	@printf "$(GREEN)==> Ejecting SD card$(RESET)\n"
	./${MOUNT_PREFACE}scripts/eject.sh

local: $(KERNEL_IMG) $(ARMSTUB_BIN)

debug: clean
	@printf "$(YELLOW)==> Rebuilding with DEBUG=1$(RESET)\n"
	$(MAKE) DEBUG=1

$(KERNEL_IMG): $(TARGET)
	@mkdir -p $(PROD_DIR)
	@printf "$(BLUE)==> Generating kernel image: %s$(RESET)\n" "$@"
	$(OBJCOPY) -O binary $^ $@

$(TARGET): $(OBJS) $(BIN_DIR)/font.o
	@printf "$(BLUE)==> Linking kernel executable$(RESET)\n"
	$(LINKER) -o $@ $^ -T $(LINKERFILE)

# Rule for C files
$(BIN_DIR)/%.o: $(SRC_DIR)/%.c
	@printf "$(GREEN)==> CC %s$(RESET)\n" "$<"
	@mkdir -p $(dir $@)
	$(CC) -c $< -o $@ $(CFLAGS) $(INCLUDES) -MMD

# Rule for Kernel Assembly files
$(BIN_DIR)/%_s.o: $(SRC_DIR)/%.S
	@printf "$(GREEN)==> AS %s$(RESET)\n" "$<"
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -o $@ -c $< $(INCLUDES)

# Rule for Armstub
$(ARMSTUB_BIN): $(BIN_DIR)/armstub/armstub_s.o
	@printf "$(BLUE)==> Linking armstub$(RESET)\n"
	@mkdir -p $(PROD_DIR)
	$(LINKER) --section-start=.text=0 -o $(BIN_DIR)/armstub/armstub.elf $^
	$(OBJCOPY) -O binary $(BIN_DIR)/armstub/armstub.elf $@

# Fixed Armstub Object Rule
$(BIN_DIR)/armstub/armstub_s.o: src/armstub/armstub.S
	@printf "$(GREEN)==> CC %s$(RESET)\n" "$<"
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@ -MMD

$(BIN_DIR)/font.o: $(SRC_DIR)/fonts/tamzen10x20.psf
	@printf "$(BLUE)==> Embedding font$(RESET)\n"
	@mkdir -p $(dir $@)
	$(LINKER) -r -b binary $< -o $@

clean:
	@printf "$(YELLOW)==> Cleaning build artifacts$(RESET)\n"
	rm -rf $(BIN_DIR) $(TARGET) objdump.S screenlog.0

asm: local
	aarch64-none-elf-objdump -d $(TARGET) > objdump.S

# Include dependency files generated by -MMD
-include $(OBJS:.o=.d)
-include $(BIN_DIR)/armstub/armstub_s.d